title: Jordan Axel Hernández Mercado
logo: /assets/img/me.jpg
email: mercado_axel@hotmail.com
description: Software Engineer
show_downloads: true
google_analytics: G-ZLK2GHB055
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: 🇲🇽 México, Jalisco, Guadalajara
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/Superkunair
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin" aria-hidden="true"></i>
    link: https://www.linkedin.com/in/jordan-axel-hernandez-mercado-6ba417170/
  - name: "+52 3327905984"
    icon: <i class="fa fa-phone"></i>

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]
